apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
spec:
  type: NodePort
  ports:
  - port: 8050
    targetPort: 80
    nodePort: 31500
  selector:
    app: nginx-deploy
